fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    registry: git://github.com/puppetlabs/puppetlabs-registry.git
  symlinks:
    icsurvey: "#{source_dir}"
    cicserver: "#{source_dir}"